export const DEMO_VIDEOS = [
  {
    id: "1",
    title: "Walking by Faith, Not by Sight",
    titleAm: "በእምነት መጓዝ፣ በእይታ አይደለም",
    category: "sunday",
    categoryLabel: "Sunday Teaching",
    duration: "58:24",
    date: "May 11, 2025",
    teacher: "Minister Bereket Negash",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    emoji: "🕊️",
    views: "1.2K",
  },
  {
    id: "2",
    title: "The Power of Prayer – Fasting Series Part 3",
    titleAm: "የጸሎት ኃይል – የጾም ተከታታይ ክፍል 3",
    category: "prayer",
    categoryLabel: "Prayer Teaching",
    duration: "44:10",
    date: "May 4, 2025",
    teacher: "Minister Bereket Negash",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "",
    emoji: "🙏",
    views: "980",
  },
  {
    id: "3",
    title: "Understanding the Beatitudes – Matthew 5",
    titleAm: "የደስታ ቃላት – ማቴዎስ 5",
    category: "bible",
    categoryLabel: "Bible Study",
    duration: "1:12:30",
    date: "Apr 27, 2025",
    teacher: "Minister Bereket Negash",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "",
    emoji: "📖",
    views: "756",
  },
  {
    id: "4",
    title: "Youth Rising: Your Purpose in Christ",
    titleAm: "ወጣቶች ይነሱ: ዓላማዎ በክርስቶስ",
    category: "youth",
    categoryLabel: "Youth Teaching",
    duration: "38:50",
    date: "Apr 20, 2025",
    teacher: "Minister Bereket Negash",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "",
    emoji: "⚡",
    views: "1.5K",
  },
  {
    id: "5",
    title: "Overcoming Fear Through the Word of God",
    titleAm: "በእግዚአብሔር ቃል ፍርሃትን ማሸነፍ",
    category: "life",
    categoryLabel: "Christian Life",
    duration: "51:15",
    date: "Apr 13, 2025",
    teacher: "Minister Bereket Negash",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "",
    emoji: "💪",
    views: "620",
  },
  {
    id: "6",
    title: "My Testimony of Healing and Restoration",
    titleAm: "የፈውስ እና የመልስ ምስክርነቴ",
    category: "testimony",
    categoryLabel: "Testimony",
    duration: "25:40",
    date: "Apr 6, 2025",
    teacher: "Minister Bereket Negash",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "",
    emoji: "✨",
    views: "890",
  },
  {
    id: "7",
    title: "Grace That Covers Every Sin",
    titleAm: "ሁሉንም ኃጢአት የሚሸፍን ጸጋ",
    category: "sunday",
    categoryLabel: "Sunday Teaching",
    duration: "1:02:00",
    date: "Mar 30, 2025",
    teacher: "Minister Bereket Negash",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "",
    emoji: "🌿",
    views: "1.1K",
  },
];

export const DEMO_PRAYERS = [
  {
    id: "morning",
    title: "Morning Prayer",
    titleAm: "የጠዋት ጸሎት",
    emoji: "🌅",
    sub: "Start with God",
    subAm: "ከእግዚአብሔር ጋር ጀምር",
    bg: "#e8f6fd",
    text: "Heavenly Father, I thank You for this new day. As the morning light breaks, I surrender this day to You. Guide my steps, guard my heart, and let Your glory be seen in all I do. In Jesus' name, Amen.",
    textAm: "ሰማያዊ አባታችን፣ ለዚህ አዲስ ቀን አመሰግናለሁ። ጠዋቱ ሲበራ ይህን ቀን ለአንተ አስረክባለሁ። ርምጃዬን ምራ፣ ልቤን ጠብቅ፣ ክብርህ በማደርገው ሁሉ ይታይ። በኢየሱስ ስም፣ አሜን።",
  },
  {
    id: "night",
    title: "Night Prayer",
    titleAm: "የምሽት ጸሎት",
    emoji: "🌙",
    sub: "End with gratitude",
    subAm: "ምስጋናን ይዘህ ጨርስ",
    bg: "#f3f0ff",
    text: "Lord, as this day ends, I thank You for Your protection and provision. Forgive me where I fell short. Cover me and my family as we rest. Let Your peace guard our sleep. In Jesus' name, Amen.",
    textAm: "ጌታ ሆይ፣ ይህ ቀን ሲጠናቀቅ፣ ለጥበቃህ እና ለቁሳቁስህ አመሰግናለሁ። ወድቄ ባለሁ ቦታ ምራ። ስናርፍ እኔን እና ቤተሰቤን ሸፍን። ሰላምህ ወደ እንቅልፋችን ይጠብቅ። በኢየሱስ ስም፣ አሜን።",
  },
  {
    id: "family",
    title: "Family Prayer",
    titleAm: "የቤተሰብ ጸሎት",
    emoji: "👨‍👩‍👧",
    sub: "Pray together",
    subAm: "አብረው ጸልዩ",
    bg: "#f0fff4",
    text: "Father God, I lift up my family before Your throne today. Bless each member. Protect our children, strengthen our marriage, and let Your love be the foundation of our home. Amen.",
    textAm: "አባት እግዚአብሔር ሆይ፣ ዛሬ ቤተሰቤን ወደ ዙፋንህ ፊት አቀርባለሁ። እያንዳንዱን አባል ባርክ። ልጆቻችንን ጠብቅ፣ ጋብቻችንን አጠናክር፣ ፍቅርህ የቤታችን መሠረት ይሁን። አሜን።",
  },
  {
    id: "healing",
    title: "Healing Prayer",
    titleAm: "የፈውስ ጸሎት",
    emoji: "💊",
    sub: "Believe & receive",
    subAm: "እመን እና ተቀበል",
    bg: "#fff9e6",
    text: "Lord Jesus, You are the healer. By Your stripes I am healed. I declare healing over my body, mind, and spirit. Touch every area of sickness and restore me to full health. In Your powerful name, Amen.",
    textAm: "ጌታ ኢየሱስ ሆይ፣ አንተ ፈዋሹ ነህ። በቁስልህ ተፈወስሁ። በሰውነቴ፣ አዕምሮዬ፣ እና መንፈሴ ላይ ፈውስ እናገራለሁ። ሁሉንም የሕመም ቦታ ዳሰስ እና ወደ ሙሉ ጤናዬ መልሰኝ። አሜን።",
  },
  {
    id: "protection",
    title: "Protection Prayer",
    titleAm: "ጥበቃ ጸሎት",
    emoji: "🛡️",
    sub: "Cover your family",
    subAm: "ቤተሰብህን ሸፍን",
    bg: "#fff0f3",
    text: "Lord, I put on the full armor of God today. No weapon formed against me shall prosper. I place the blood of Jesus over my home, my family, and every place I go. You are my shield. Amen.",
    textAm: "ጌታ ሆይ፣ ዛሬ ሙሉ የእግዚአብሔር ትጥቅ ለብሻለሁ። በእኔ ላይ የተቀረፀ ምንም መሳሪያ አይሳካም። የቤቴን፣ ቤተሰቤን፣ እና እሄድበት ቦታ ሁሉ በኢየሱስ ደም ሸፍኛለሁ። አንተ ጋሻዬ ነህ። አሜን።",
  },
  {
    id: "thanksgiving",
    title: "Thanksgiving Prayer",
    titleAm: "ምስጋና ጸሎት",
    emoji: "🙌",
    sub: "Praise the Lord",
    subAm: "ጌታን አሞካሽ",
    bg: "#e8f6fd",
    text: "Lord, I thank You for life, health, salvation, family, and every blessing You have poured into my life. You have been faithful when I was faithless. Glory be to Your name forever. Amen.",
    textAm: "ጌታ ሆይ፣ ለሕይወት፣ ጤና፣ ድኅነት፣ ቤተሰብ፣ እና ባፈሰስከው ሁሉ በረከት አመሰግናለሁ። ታምኜ ባልሆን ጊዜ ታምነሃል። ክብር ለስምህ ለዘለዓለም ይሁን። አሜን።",
  },
  {
    id: "repentance",
    title: "Repentance Prayer",
    titleAm: "ንስሐ ጸሎት",
    emoji: "❤️‍🩹",
    sub: "Return to God",
    subAm: "ወደ እግዚአብሔር ተመለስ",
    bg: "#fdf4ff",
    text: "Father, I come before You with a humble heart. I confess my sins and shortcomings. Forgive me, cleanse me, and restore me to right standing with You. Thank You for Your mercy. In Jesus' name, Amen.",
    textAm: "አባት ሆይ፣ ትሑት ልብ ይዤ ወደ አንተ ፊት እቀርባለሁ። ኃጢአቶቼን እና ሰናፍቸን እናዘዛለሁ። ምረኝ፣ ነጻ አውጣኝ፣ ወደ ትክክለኛ ቦታዬ ከአንተ ጋር መልሰኝ። ለምሕረትህ አመሰግናለሁ። በኢየሱስ ስም፣ አሜን።",
  },
  {
    id: "daily",
    title: "Daily Prayer",
    titleAm: "ዕለታዊ ጸሎት",
    emoji: "☀️",
    sub: "Every day with God",
    subAm: "ሁልጊዜ ከእግዚአብሔር ጋር",
    bg: "#f0f8ff",
    text: "Lord, I choose to seek You first today before any distraction or demand. Let Your Kingdom come and Your will be done in my life. Fill me with Your Spirit and let me walk in Your purpose. Amen.",
    textAm: "ጌታ ሆይ፣ ዛሬ ከማንኛውም ትኩረት ወይም ጥያቄ በፊት አንተን ለመፈለግ እወስናለሁ። መንግሥትህ ትምጣ እና ፈቃድህ በሕይወቴ ይፈጸም። በመንፈስህ ሙላኝ እና ዓላማህ ውስጥ ላስኬደኝ። አሜን።",
  },
];

export const DEMO_BOOKS = [
  {
    id: "1",
    cover: "📖",
    bg: "#e8f6fd",
    category: "Bible Study",
    categoryAm: "የመጽሐፍ ቅዱስ ጥናት",
    title: "Foundations of Faith",
    titleAm: "የእምነት መሠረቶች",
    author: "Minister Bereket Negash",
    lang: "English",
    pdfUrl: "#",
    canDownload: true,
  },
  {
    id: "2",
    cover: "🙏",
    bg: "#fff9e6",
    category: "Prayer",
    categoryAm: "ጸሎት",
    title: "የጸሎት ኃይል",
    titleAm: "የጸሎት ኃይል",
    author: "ሚኒስተር ብርሃኑ ነጋሽ",
    lang: "አማርኛ",
    pdfUrl: "#",
    canDownload: true,
  },
  {
    id: "3",
    cover: "✝️",
    bg: "#f0fff4",
    category: "Faith",
    categoryAm: "እምነት",
    title: "Unwavering Trust in God",
    titleAm: "ሳይለዋወጥ በእግዚአብሔር ማመን",
    author: "Dr. A. Haile",
    lang: "English",
    pdfUrl: "#",
    canDownload: false,
  },
  {
    id: "4",
    cover: "🌱",
    bg: "#f3f0ff",
    category: "Discipleship",
    categoryAm: "ደቀ-መዝሙርነት",
    title: "Growing in Discipleship",
    titleAm: "በደቀ-መዝሙርነት ማደግ",
    author: "Soma Christos Church",
    lang: "English",
    pdfUrl: "#",
    canDownload: true,
  },
  {
    id: "5",
    cover: "📜",
    bg: "#fff0f3",
    category: "Amharic Resources",
    categoryAm: "አማርኛ ሀብቶች",
    title: "መጽሐፍ ቅዱስ ጥናት ዘዴ",
    titleAm: "መጽሐፍ ቅዱስ ጥናት ዘዴ",
    author: "ቡድን ሚኒስቴሪ",
    lang: "አማርኛ",
    pdfUrl: "#",
    canDownload: true,
  },
  {
    id: "6",
    cover: "❤️",
    bg: "#f0f8ff",
    category: "Christian Life",
    categoryAm: "ክርስቲያናዊ ሕይወት",
    title: "Living the Christian Life in a Modern World",
    titleAm: "በዘመናዊ ዓለም ክርስቲያናዊ ሕይወት",
    author: "Minister Bereket Negash",
    lang: "English",
    pdfUrl: "#",
    canDownload: true,
  },
];

export const DEMO_NOTES = [
  {
    id: "1",
    title: "Walking by Faith",
    titleAm: "በእምነት መጓዝ",
    verse: "Hebrews 11:1",
    learned: "Faith is the substance of things hoped for, the evidence of things not seen. True faith acts before it sees.",
    godSpoke: "God told me to trust the process even when I cannot see the outcome. Stop waiting for certainty before obeying.",
    action: "Spend 15 minutes in faith prayer daily. Take one step of obedience this week.",
    prayerPt: "Lord strengthen my faith. Help me to walk forward even in uncertainty.",
    date: "May 11, 2025",
  },
  {
    id: "2",
    title: "The Power of Prayer",
    titleAm: "የጸሎት ኃይል",
    verse: "James 5:16",
    learned: "The prayer of a righteous person is powerful and effective. Fasting adds intensity and focus to prayer.",
    godSpoke: "I need to be more consistent and less distracted in my prayer life.",
    action: "Join the 6 AM morning prayer group on WhatsApp. Fast every Tuesday.",
    prayerPt: "Give me a heart of prayer. Make intercession natural for me.",
    date: "May 4, 2025",
  },
];

export const DAILY_VERSE = {
  text: '"Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him."',
  textAm: '"ከሁሉ ልብህ በእግዚአብሔር ታመን፤ ወደ ራስህ ማስተዋልም አትደገፍ፤ በሁሉ መንገዶችህ እርሱን እወቅ።"',
  ref: "Proverbs 3:5-6",
};
